routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('index');
});

Auth::routes();

Route::get('/dashboard', 'HomeController@index')->name('dashboard');
Route::get('/profiles/trash','ProfileController@showTrash')->name('profiles.trash');
Route::get('/profiles/{id}/restore','ProfileController@restore')->name('profiles.restore');
Route::get('/profiles/{id}/delete','ProfileController@delete')->name('profiles.delete');
Route::post('/profiles/destroy-many','ProfileController@destroyMany')->name('profiles.destroy-many');
Route::resource('/profiles','ProfileController');
Route::get('/menus/trash','MenuController@showTrash')->name('menus.trash');
Route::get('/menus/{id}/restore','MenuController@restore')->name('menus.restore');
Route::get('/menus/{id}/delete','MenuController@delete')->name('menus.delete');
Route::get('/menus/{menu}/activate','MenuController@activate')->name('menus.activate');
Route::get('/menus/{menu}/deactivate','MenuController@deactivate')->name('menus.deactivate');
Route::post('/menus/destroy-many','MenuController@destroyMany')->name('menus.destroy-many');
Route::resource('/menus','MenuController');

app/User.php
<?php

namespace App;

use App\Notifications\NotificationResetPassword;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;

class User extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    /**
     * Send the password reset notification.
     *
     * @param  string  $token
     * @return void
     */
    public function sendPasswordResetNotification($token)
    {
        $this->notify(new NotificationResetPassword($token, $this));
    }

    public function profiles()
    {
        return $this->belongsToMany('App\Models\Profile','users_profiles')->withTimestamps();
    }

    public function getRolesAttribute()
    {
        return $this->profiles->pluck('name')->implode(',');
    }
}

resources/views/layouts/app.blade.php
<!DOCTYPE html>
<html lang="{{ config('app.locale') }}">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- CSRF Token -->
    <meta name="csrf-token" content="{{ csrf_token() }}">

    <title>{{ config('app.name', 'Laravel') }}</title>

    <!-- Styles -->
    <link href="{{ asset('css/app.css') }}" rel="stylesheet">
    <link href="{{ asset('css/font-awesome.css') }}" rel="stylesheet">
</head>
<body>
    <div id="app">
        <nav class="navbar navbar-default navbar-static-top">
            <div class="container">
                <div class="navbar-header">

                    <!-- Collapsed Hamburger -->
                    <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#app-navbar-collapse">
                        <span class="sr-only">Toggle Navigation</span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>

                    <!-- Branding Image -->
                    <a class="navbar-brand" href="{{ url('/') }}">
                        {{ config('app.name', 'Laravel') }}
                    </a>
                </div>

                <div class="collapse navbar-collapse" id="app-navbar-collapse">
                    <!-- Left Side Of Navbar -->
                    <ul class="nav navbar-nav">
                        &nbsp;
                    </ul>

                    <!-- Right Side Of Navbar -->
                    <ul class="nav navbar-nav navbar-right">
                        <!-- Authentication Links -->
                        @if (Auth::guest())
                            <li><a href="{{ route('login') }}">{{ trans('auth.title') }}</a></li>
                            <li><a href="{{ route('register') }}">{{ trans('register.title') }}</a></li>
                        @else
                            <li class="dropdown">
                                <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">
                                    {{ Auth::user()->name }} <small>({{ Auth::user()->roles }})</small> <span class="caret"></span>
                                </a>
                                <ul class="dropdown-menu" role="menu">
                                    <li>
                                        <a href="{{ url('dashboard') }}"><i class="fa fa-tachometer"></i>&nbsp;Home</a>
                                    </li>
                                    @forelse(auth()->user()->profiles as $profile)
                                        @forelse($profile->menus as $menu)
                                            <li><a href="{{ url($menu->location) }}"><i class="{{ $menu->icon }}"></i>&nbsp;{{ $menu->name }}</a></li>
                                        @empty
                                        @endforelse
                                    @empty
                                    @endforelse
                                    <li>
                                        <a href="{{ route('logout') }}"
                                            onclick="event.preventDefault();
                                                     document.getElementById('logout-form').submit();">
                                                     <i class="fa fa-sign-out"></i>&nbsp;
                                            Sair
                                        </a>

                                        <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
                                            {{ csrf_field() }}
                                        </form>
                                    </li>
                                </ul>
                            </li>
                        @endif
                    </ul>
                </div>
            </div>
        </nav>

        @yield('content')
    </div>

    <!-- Scripts -->
    <script src="{{ asset('js/app.js') }}"></script>
    <script src="{{ asset('js/jquery-3.2.1.min.js') }}"></script>
    
    @yield('scripts')
</body>
</html>